# # class MyError(Exception):
# #     # Constructor or Initializer
# #     def __init__(self,value):
# #         self.value = value
# #         pass
 
# #     # __str__ is to print() the value
# #     def __str__(self):
# #         return(repr(self.value))


# # try:
# #     raise(MyError(5*5)) 
 
# # # Value of Exception is stored in error
# # except MyError as error: 
# #     # print(error.args[0]) 
# #     print('A New Exception occurred:', error.value) 


# class sonal(object):
#     def __init__(self,lname,ssn,boss):
#         self.lname=lname
#         self.ssn=ssn
#         self.boss=boss

#     def greater(other,self):
#         print(type(self),1)
#         print(type(other),5)
#         return self.lname+other.lname

# class kirtan(object):
#     def __init__(self,lname,ssn,boss):
#         self.lname=lname
#         self.ssn=ssn
#         self.boss=boss
# def sooo():
#     pass

# def su(a,b,sooo()):
#     return a+b
# print(su(2,6,u))
# sooo()=5

# u()

# print(repr('2') + ' is what?')